spring.application.name=SimpleOuth
# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23li9iaOdsfKQ72EE3
spring.security.oauth2.client.registration.github.client-secret=c3dbad2818e6a9a20c9d2b55c25515cdc1cbb5b4
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/github
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user

