spring.application.name=SimpleOuth
# GitHub OAuth2 Configuration
spring.security.oauth2.client.registration.github.client-id=Ov23li9iaOdsfKQ72EE3
spring.security.oauth2.client.registration.github.client-secret=08fdc5a27d8959ba3a97bc628612fc1628505cf2
